# Introduction

This notebook shows an example of relaxing the LiFePO4 crystal.

In [ ]:
import warnings

import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.util.coord import pbc_diff

from m3gnet.models import Relaxer

for category in (UserWarning, DeprecationWarning):
    warnings.filterwarnings("ignore", category=category, module="tensorflow")

: 

In [ ]:
import tensorflow as tf

tf.config.experimental.list_physical_devices("GPU")

: 

In [3]:
mpr = MPRester()
lfp = mpr.get_structure_by_material_id("mp-19017")  # This is LiFePO4.

lfp_strained = lfp.copy()  # We create a copy.
# Create a random strain between -5% and 5% for each direction
strains = np.random.uniform(low=-0.05, high=0.05, size=3)
lfp_strained.apply_strain(strains)
# In addition to the lattice strains, we also perturb the atoms by a distance of 0.1 angstrom.
lfp_strained.perturb(0.1)

In [4]:
relaxer = Relaxer()
relax_results: dict
%time relax_results = relaxer.relax(lfp_strained)
relaxed = relax_results["final_structure"]

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-07-10 12:50:06.141194: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-10 12:50:06.141334: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-07-10 12:50:09.946045: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-07-10 12:50:09.957309: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


NotFoundError: Graph execution error:

Detected at node 'gradients/m3g_net/graph_network_layer/gated_atom_update/UnsortedSegmentSum_grad/and' defined at (most recent call last):
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
      app.start()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 712, in start
      self.io_loop.start()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
      self._run_once()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
      handle._run()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
      await result
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
      res = shell.run_cell(
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2881, in run_cell
      result = self._run_cell(
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2936, in _run_cell
      return runner(coro)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3135, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/ipykernel_9555/3879703908.py", line 2, in <cell line: 2>
      get_ipython().run_line_magic('time', 'relax_results = relaxer.relax(lfp_strained)')
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2305, in run_line_magic
      result = fn(*args, **kwargs)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/IPython/core/magics/execution.py", line 1316, in time
      exec(code, glob, local_ns)
    File "<timed exec>", line 1, in <module>
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/m3gnet/models/_dynamics.py", line 167, in relax
      optimizer = self.opt_class(atoms, **kwargs)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/optimize/fire.py", line 54, in __init__
      Optimizer.__init__(self, atoms, restart, logfile, trajectory,
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/optimize/optimize.py", line 234, in __init__
      self.set_force_consistent()
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/optimize/optimize.py", line 325, in set_force_consistent
      self.atoms.get_potential_energy(force_consistent=True)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/constraints.py", line 2420, in get_potential_energy
      atoms_energy = self.atoms.get_potential_energy(
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/atoms.py", line 728, in get_potential_energy
      energy = self._calc.get_potential_energy(
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/calculators/calculator.py", line 709, in get_potential_energy
      energy = self.get_property('energy', atoms)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
      self.calculate(atoms, [name], system_changes)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/m3gnet/models/_dynamics.py", line 86, in calculate
      results = self.potential.get_efs_tensor(graph_list, include_stresses=self.compute_stress)
    File "/opt/homebrew/Caskroom/miniconda/base/envs/m3gnet/lib/python3.10/site-packages/m3gnet/models/_base.py", line 188, in get_efs_tensor
      derivatives = tape.gradient(energies, derivatives)
Node: 'gradients/m3g_net/graph_network_layer/gated_atom_update/UnsortedSegmentSum_grad/and'
No registered 'BroadcastTo' OpKernel for 'GPU' devices compatible with node {{node gradients/m3g_net/graph_network_layer/gated_atom_update/UnsortedSegmentSum_grad/and}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_BOOL, Tidx=DT_INT32, _XlaHasReferenceVars=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"
	.  Registered:  device='XLA_CPU_JIT'; Tidx in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 16005131165644881776, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='GPU'; T in [DT_FLOAT]
  device='DEFAULT'; T in [DT_INT32]
  device='CPU'; T in [DT_UINT64]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_UINT32]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_RESOURCE]
  device='CPU'; T in [DT_VARIANT]

	 [[PartitionedCall/gradients/m3g_net/graph_network_layer/gated_atom_update/UnsortedSegmentSum_grad/and]] [Op:__inference_get_efs_tensor_7426]

NameError: name 'relax_results' is not defined

Note that the relaxation only took < 20s.

In [13]:
print(f"Original lattice parameters are {[round(x, 3) for x in lfp.lattice.abc]}")
print(f"Strained lattice parameters are {[round(x, 3) for x in lfp_strained.lattice.abc]}")
print(f"Relaxed lattice parameters are {[round(x, 3) for x in relaxed.lattice.abc]}")

Original lattice parameters are [4.746, 10.444, 6.09]
Strained lattice parameters are [4.751, 10.912, 5.849]
Relaxed lattice parameters are [4.75, 10.444, 6.106]


In [5]:
print(f"Diff in fractional coords:\n{pbc_diff(lfp.frac_coords, relaxed.frac_coords)}")

Diff in fractional coords:
[[-0.00387997 -0.00279335 -0.00278419]
 [-0.0105322   0.00017964 -0.00350815]
 [ 0.00567224 -0.00023636 -0.00763473]
 [ 0.00193715  0.00778645 -0.0020107 ]
 [ 0.00225437  0.00170045  0.00172863]
 [ 0.00097444  0.00094502  0.00388633]
 [ 0.00345818  0.00368189  0.0024407 ]
 [-0.00038704  0.00417402  0.00208854]
 [ 0.00349925  0.00451124 -0.00329377]
 [ 0.00301799  0.00162616  0.00426465]
 [-0.00035351  0.0040381   0.00160278]
 [-0.00239293  0.00165153 -0.00127454]
 [ 0.00438634  0.00427503 -0.00071235]
 [ 0.00422623  0.002672    0.00449112]
 [-0.00079353  0.0043336  -0.00153869]
 [-0.0033543   0.00193773 -0.00280839]
 [-0.00151142  0.00393776 -0.00398973]
 [-0.00481124  0.00160034 -0.00323102]
 [ 0.00471888  0.0048146  -0.00417542]
 [ 0.0007874   0.00072707  0.00049835]
 [ 0.0041545   0.00410332 -0.00345285]
 [ 0.00412935  0.0025092   0.00449315]
 [ 0.00459609  0.0002639   0.00462091]
 [ 0.00272673  0.00434772 -0.00369026]
 [ 0.00018383  0.00028395  0.00456975

Quite clealy, the relaxation using the M3GNet universal IAP has brought the lattice parameters much closer to the original DFT one and the coordinates are also within $10^{-3}$ of the original fractional coordinates.